### ISSUE TITLE
"main.py" execute error

### ISSUE THREAD

**Issue by arith3** [habrman/FaceRecognition#2] opened 2018-01-23 07:44 UTC
Hello.
I got some problem when execute your codes.
```sh
me~~~$ python3 main.py ./20170512-110547/ ./pics/
Couldn't import dot_parser, loading of dot files will not be possible.
2018-01-23 16:37:29.142315: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-01-23 16:37:29.541278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.45GiB
2018-01-23 16:37:29.880962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:03:00.0
totalMemory: 10.91GiB freeMemory: 10.32GiB
2018-01-23 16:37:30.222775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 2 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:81:00.0
totalMemory: 10.91GiB freeMemory: 10.32GiB
2018-01-23 16:37:30.222992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-01-23 16:37:30.223055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 2
2018-01-23 16:37:30.223067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y N
2018-01-23 16:37:30.223075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y N
2018-01-23 16:37:30.223083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 2:   N N Y
2018-01-23 16:37:30.223103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2018-01-23 16:37:30.223113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-01-23 16:37:30.223122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:2) -> (device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:81:00.0, compute capability: 6.1)
Model directory: ./20170512-110547/
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:479: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "main.py", line 141, in main
    id_dataset = id_data.get_id_data(args.id_folder[0], pnet, rnet, onet, sess, embeddings, images_placeholder, phase_train_placeholder)
  File "/u/data/arith/face/FaceRecognition/id_data.py", line 31, in get_id_data
    id_dataset[i].embedding = emb[i, :]
IndexError: index 5 is out of bounds for axis 0 with size 5
```

I didn't solve this problem.
Could you help me?

**Comment by sayak1711** [comment] 2018-01-29 06:08
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "main.py", line 141, in main
    id_dataset = id_data.get_id_data(args.id_folder[0], pnet, rnet, onet, sess, embeddings, images_placeholder, phase_train_placeholder)
  File "F:\fr_tensor\FaceRecognition\id_data.py", line 25, in get_id_data
    aligned_images = align_id_dataset(id_dataset, pnet, rnet, onet)
  File "F:\fr_tensor\FaceRecognition\id_data.py", line 41, in align_id_dataset
    face_patches, _, _ = detect_and_align.align_image(image, pnet, rnet, onet)
  File "F:\fr_tensor\FaceRecognition\detect_and_align.py", line 14, in align_image
    bounding_boxes, landmarks = detect_face(img, pnet, rnet, onet)
  File "F:\fr_tensor\FaceRecognition\detect_and_align.py", line 468, in detect_face
    img_y = np.transpose(img_x, (0, 2, 1, 3))
  File "\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by habrman** [comment] 2018-02-15 19:15
I haven't worked on this for quite some time but I'll take a look on it as soon as I can. Seems to be a fairly simple problem. These are two different problems.

@Sayak1711: are you using any grayscale images?
@Namori3: How did you structure your id-folder with all the images?

**Comment by habrman** [comment] 2018-02-15 19:52
I haven't actually looked at it yet but these are two different problems.

@Sayak1711: are you using any grayscale images?
@Namori3: How did you structure your id-folder with all the images?

**Comment by habrman** [comment] 2018-02-17 10:19
I can confirm that the problem @sayak1711 has is due to grayscale images. I've pushed an update to handle this.

@namori3 I can't reproduce your error. Can you give me any additional information?

**Comment by sayak1711** [comment] 2018-02-20 05:43
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "main.py", line 141, in main
    id_dataset = id_data.get_id_data(args.id_folder[0], pnet, rnet, onet, sess, embeddings, images_placeholder, phase_train_placeholder)
  File "F:\fr_tensor\FaceRecognition\id_data.py", line 31, in get_id_data
    id_dataset[i].embedding = emb[i, :]
IndexError: index 41 is out of bounds for axis 0 with size 41

**Comment by sayak1711** [comment] 2018-02-20 05:46
Yes @habrman  I was using grayscale images. It is working fine now with normal photo. Thanks.

**Comment by habrman** [comment] 2018-02-20 10:06
@sayak1711 it should now be working with the original photo now as well

**Comment by habrman** [comment] 2018-02-25 09:48
I'm closing this issue since I can't reproduce the problem that @namori3 had and the other problem is solved.

**Closed as completed by habrman** 2018-02-25 09:48 UTC
